### ISSUE TITLE
Serialization error when using helm to install a chart with Java

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-java#629]
### What happened?

Error when using helm to install a chart with Java.

### Steps to reproduce

```java
return new Release("nginx",
                ReleaseArgs.builder()
                        .chart("nginx-ingress")
                        .version("1.24.4")
                        .repositoryOpts(RepositoryOptsArgs.builder().repo("https://charts.helm.sh/stable").build())
                        .valueYamlFiles(new FileAsset("./values.yaml"))
                        .build(),
                CustomResourceOptions.builder()
                        .provider(provider)
                        .build());
```

### Expected Behavior

Working code.

### Actual Behavior

```
java.lang.UnsupportedOperationException: Convert [com.pulumi.kubernetes.helm.sh_v3.Release.resourceNames]: Error converting 'com.google.common.collect.RegularImmutableMap' to 'TypeShape{type=interface java.util.Map, parameters=[TypeShape{type=class java.lang.String, parameters=[]}, TypeShape{type=interface java.util.List, parameters=[]}]}'. Expected a parameter type for the List, got none
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment]
@t0yv0 do you want to keep this on the triage queue until you get to it?

**Comment by t0yv0** [comment]
Ah sorry about that, I just want to get it on @pawelprazak radar. This does need fixing when possible so I can remove the label.

**Comment by pawelprazak** [comment]
This is the cause for the error, the annotation for exports does not support nested generic types, so List is raw/untyped.
And the Converter validation is strict in this case currently.
```
@Export(name="resourceNames", type=Map.class, parameters={String.class, List.class})
private Output</* @Nullable */ Map<String,List<String>>> resourceNames;
```

The easiest solution would be to relax the converter validation, but I'm not sure about the second order consequences.

I don't expect that overcoming java annotations limits would be easy or readable, as discussed here https://stackoverflow.com/a/35776898/539481

**Comment by hnicke** [comment]
I am still experiencing this problem.

Here is a complete stack definitition:

```java
import com.pulumi.Context
import com.pulumi.Pulumi
import com.pulumi.kubernetes.helm.v3.Release
import com.pulumi.kubernetes.helm.v3.ReleaseArgs
import com.pulumi.kubernetes.helm.v3.inputs.RepositoryOptsArgs
import com.pulumi.resources.CustomResourceOptions

object App {
    @JvmStatic
    fun main(args: Array<String>) {
        Pulumi.run { pulumiContext: Context ->
            Release("nginx",
                ReleaseArgs.builder()
                    .chart("nginx-ingress")
                    .version("1.24.4")
                    .repositoryOpts(RepositoryOptsArgs.builder().repo("https://charts.helm.sh/stable").build())
                    .build(),
                CustomResourceOptions.builder()
                    .build());
        }
    }
}

```

`pulumi up` fails with the following exception:
`java.lang.UnsupportedOperationException: Convert [com.pulumi.kubernetes.helm.v3.Release.resourceNames]: Error converting 'com.google.common.collect.RegularImmutableMap' to 'TypeShape{type=interface java.util.Map, parameters=[TypeShape{type=class java.lang.String, parameters=[]}, TypeShape{type=interface java.util.List, parameters=[]}]}'. Expected a parameter type for the List, got none`

Using pulumi 3.43.1 with pulumi-java 0.6.0.
The changelog suggests this was fixed with 0.6.0 which seems to be false.

This issue should get reopened.

**Comment by pawelprazak** [comment]
@hnicke I'm speculating here, but there is a possibility that an old kubernetes provider is used and this my re-surface the problem.

It is possible to remove all kubernetes provider versions from local cache using this command:
```
pulumi plugin rm resource kubernetes
```
Afterwards, a new version would be downloaded automatically and will be visible in the output of `pulumi plugin ls`.

**Comment by hnicke** [comment]
Btw, in the `build.gradle.kts`, I'm using pulumi-kubernetes v3.21.4.

Output of `pulumi plugin ls` (before removing the plugin):
```
NAME           KIND      VERSION  SIZE    INSTALLED      LAST USED
azure          resource  4.11.0   235 MB  11 months ago  15 seconds ago
azure          resource  4.6.0    229 MB  1 year ago     15 seconds ago
azure          resource  4.1.0    225 MB  1 year ago     15 seconds ago
azure          resource  3.53.0   219 MB  2 years ago    15 seconds ago
azure          resource  3.50.0   216 MB  2 years ago    15 seconds ago
azure          resource  3.48.0   222 MB  2 years ago    15 seconds ago
azure          resource  3.4.0    177 MB  2 years ago    15 seconds ago
azure          resource  1.9.0    156 MB  2 years ago    15 seconds ago
azure-native   resource  1.19.0   42 MB   11 months ago  15 seconds ago
azure-native   resource  1.9.0    42 MB   1 year ago     15 seconds ago
azure-native   resource  1.4.0    41 MB   1 year ago     15 seconds ago
azure-native   resource  0.7.1    43 MB   2 years ago    15 seconds ago
azure-nextgen  resource  0.6.1    42 MB   2 years ago    15 seconds ago
azuread        resource  4.3.0    41 MB   11 months ago  15 seconds ago
azuread        resource  4.2.0    41 MB   1 year ago     15 seconds ago
azuread        resource  4.0.0    40 MB   1 year ago     15 seconds ago
azuread        resource  3.5.1    38 MB   2 years ago    15 seconds ago
azuread        resource  3.4.0    44 MB   2 years ago    15 seconds ago
azuread        resource  2.1.0    41 MB   2 years ago    15 seconds ago
azuread        resource  1.4.0    40 MB   2 years ago    15 seconds ago
gcp            resource  6.41.0   125 MB  3 days ago     15 seconds ago
gcp            resource  6.37.0   124 MB  1 month ago    15 seconds ago
gcp            resource  6.36.0   124 MB  1 month ago    15 seconds ago
gcp            resource  6.23.0   122 MB  4 months ago   15 seconds ago
kubernetes     resource  3.21.4   83 MB   3 days ago     15 seconds ago
kubernetes     resource  3.21.2   83 MB   1 month ago    15 seconds ago
kubernetes     resource  3.21.1   83 MB   1 month ago    15 seconds ago
kubernetes     resource  3.19.1   77 MB   4 months ago   15 seconds ago
kubernetes     resource  3.5.1    67 MB   11 months ago  15 seconds ago
kubernetes     resource  3.3.0    78 MB   1 year ago     15 seconds ago
kubernetes     resource  3.1.1    78 MB   1 year ago     15 seconds ago
kubernetes     resource  2.8.4    77 MB   2 years ago    15 seconds ago
kubernetes     resource  2.8.2    77 MB   2 years ago    15 seconds ago
kubernetes     resource  2.8.1    77 MB   2 years ago    15 seconds ago
kubernetes     resource  2.0.0    52 MB   2 years ago    15 seconds ago
kubernetes     resource  1.4.1    50 MB   2 years ago    15 seconds ago
random         resource  4.8.2    34 MB   1 month ago    15 seconds ago
random         resource  4.6.0    32 MB   4 months ago   15 seconds ago
random         resource  4.2.0    31 MB   1 year ago     15 seconds ago
random         resource  4.0.0    31 MB   1 year ago     15 seconds ago
random         resource  3.1.1    30 MB   2 years ago    15 seconds ago
random         resource  3.1.0    30 MB   2 years ago    15 seconds ago

TOTAL plugin cache size: 3.8 GB
```

I removed the cached kubernetes plugins:
```

This will remove 12 plugins from the cache:
    resource kubernetes-1.4.1
    resource kubernetes-2.0.0
    resource kubernetes-2.8.1
    resource kubernetes-2.8.2
    resource kubernetes-2.8.4
    resource kubernetes-3.1.1
    resource kubernetes-3.19.1
    resource kubernetes-3.21.1
    resource kubernetes-3.21.2
    resource kubernetes-3.21.4
    resource kubernetes-3.3.0
    resource kubernetes-3.5.1
Please confirm that this is what you'd like to do by typing `yes`: yes
```
I've removed all the other plugins from the cache as well.

During execution of the next `pulumi up`, it downloaded the kubernetes plugin again:
```
Downloading plugin kubernetes v3.21.4: 34.29 MiB / 34.29 MiB [======] 100.00% 3s
```
However, I'm still experiencing the same error (`Expected a parameter type for the List, got none`).

Output of `pulumi about`:
```
CLI          
Version      3.43.1
Go Version   go1.19.1
Go Compiler  gc

Plugins
NAME        VERSION
gcp         6.41.0
java        unknown
kubernetes  3.21.4
random      4.8.2

Host     
OS       arch
Version  
Arch     x86_64

This project is written in java: executable='/usr/bin/java' version='openjdk 19.0.1 2022-10-18
OpenJDK Runtime Environment (build 19.0.1+10)
OpenJDK 64-Bit Server VM (build 19.0.1+10, mixed mode)' java='/usr/bin/java' javac='19.0.1'
```

**Comment by pawelprazak** [comment]
Thank you for trying and for detailed response, it was worth a try ;)

It's unfortunate that the problem persists, we'll need to take a closer look.

**Comment by jensbarthel** [comment]
We are experiencing this problem using kotlin as well, when:
-  trying to set site config args for a function web app
- trying to list namespace keys of service bus

**Comment by jensbarthel** [comment]
Update:
We found out that this seems to have been fixed in v0.6.0
Thanks guys :+1:

**Comment by benediktarnold** [comment]
I can confirm that this issue still exists with pulumi-java 0.6.0. Even tried the latest kubernetes alpha plugin and it didn't make a difference.

**Comment by hnicke** [comment]
Can confirm that unforntunately the issue still persists with all pulumi dependencies being up-to-date.

**Comment by hnicke** [comment]
As of now, all helm chart installations are working fine for me! :partying_face: 
I'm using the latest version of all plugins and pulumi itself.
